### PR TITLE
Octernship assignment submission

### PR DESCRIPTION
**Pull request by dibenzepin**
I'm not quite sure whether how exactly to submit this assignment, I've made a branch in the GitHub Classroom generated one and opened a [PR there](https://github.com/rustdesk-org/authenticate-without-polkit-poopsicles/pull/1) but since a few people are making PRs against this I figured I might as well do that too.

I had to rebase all my commits against [rustdesk-org/Octernships_Project](https://github.com/rustdesk-org/Octernships_Project/), but all my changes were made before the deadline (the timestamps in the private repo can be used to verify this)

### CODE REVIEW

**Comment by devporter007** [comment]
what??? i thought we were supposed to do the pr in the specific repository github classroom created and not this template one...

**Comment by dibenzepin** [comment]
> what??? i thought we were supposed to do the pr in the specific repository github classroom created and not this template one...

yeah me too, but then there's like a bunch of people doing it here anyways

there's no central discussion so everyone is confused really

i'm just doing both

**Comment by dibenzepin** [comment]
> I'm making a copy of [my comment in the private repo](https://github.com/rustdesk-org/authenticate-without-polkit-poopsicles/pull/1#issuecomment-1599375685) over here in case this is the canonical submission way

Decided to make a recording of the app in action to make it easier to evaluate.

As said in the [README](https://github.com/poopsicles/rustdesk-octernship/blob/add-main-assignment/README.md), it checks which methods are feasible on the system it's ran, and then provides the option to switch between them.

In my WSL environment, `polkit` isn't installed (due to the lack of a desktop environment) so it doesn't offer the option. Instead `sudo` and `su` are available as a fallback. Contrary to that, my Fedora VirtualBox VM does have `polkit` so it tries to use that first, only falling back to the other options when that one fails.

You can see this demonstrated here:

## Using WSL

https://github.com/rustdesk-org/Octernships_Project/assets/87488715/2e4bb1ca-6eb4-4d94-b8fc-2e47333c6389

## Using VM

https://github.com/rustdesk-org/Octernships_Project/assets/87488715/f1a18929-8e8f-49bb-bc62-3cbef8a899cd

**Comment by dibenzepin** [comment]
@devporter007 looks like we finally got [confirmation](https://github.com/rustdesk/rustdesk/issues/2756#issuecomment-1598257695)

**Comment by devporter007** [comment]
> @devporter007 looks like we finally got [confirmation](https://github.com/rustdesk/rustdesk/issues/2756#issuecomment-1598257695)

Thanks for informing me bud, rustdesk should have made this clear early on...

**Comment by rustdesk** [comment]
Looks good.

**Comment by devporter007** [comment]
> Looks good.

you will review the pr submitted in private repos too right?

**Comment by rustdesk** [comment]
> PR there

https://github.com/rustdesk-org/authenticate-without-polkit-poopsicles/pull/1#issuecomment-1612777717

BTW, how can we mark someone to "Passing" status in the classroom page? I can not see any link or button to make this change. Also, is there any good way to remove these robot generated repos (>500 repos, no way to delete manually one by one) without api? 

image

**Comment by dibenzepin** [comment]
@rustdesk looking at the [Octernship Handbook](https://github.com/education/Octernships/blob/main/1.%20Application.md#reviewing-student-submissions-) under **Reviewing Student Submissions**, it appears you need to click the "Repository" button beside each submission to evaluate it. Perhaps there you can then mark it as "Passing".

I assume the button will take you to the private generated repo, and there'll be buttons to communicate with the student or change the status of the submission.

Unfortunately, the demo video is broken, so I'm not exactly sure how it would look like to you - I'll make sure they're notified by opening an issue.

Then you'll have to notify GitHub staff of your selections using the `Octern Selection Form` as detailed in the **Selecting candidates for your Octernship** heading.

And I see no way of removing submissions on a mass scale - becuase determining whether one is "robot-generated" might lead to inadvertently removing some human submissions. I think the best bet is to just look at the commit contents, and if it's not satisfactory, fail the submission.

Maybe you should contact them at partners-octernships@github.com for more help?

**Comment by dibenzepin** [comment]
The demo video might only be broken for me...I use a beta version of both Firefox and Windows, but I've opened an issue

education/Octernships#18

**Comment by dibenzepin** [comment]
not really sure if the public repos count towards anything at this point, so i apologise if i’m making a fuss, but #20 and #21 appear to have copied my repo contents and are attempting to pass them off as their own:

- #20 ([repo](https://github.com/ADS-bot/Octernships_Project/tree/gg)) just lifted my repo and changed the README.md - which still contains [references](https://github.com/ADS-bot/Octernships_Project/blob/b698e42025c1c6dbd8dfca3a45eb784caae6160c/README.md) to `RustBackend` and `FrontEnd` folders, which don’t exist anymore, and [native/src/api.rs](https://github.com/ADS-bot/Octernships_Project/blob/b698e42025c1c6dbd8dfca3a45eb784caae6160c/native/src/api.rs) and [lib/main.dart](https://github.com/ADS-bot/Octernships_Project/blob/b698e42025c1c6dbd8dfca3a45eb784caae6160c/lib/main.dart) contain copies of my code…comments and all
- #21 ([repo](https://github.com/Phoenix1504e/Octernships_Project/tree/main)) is smarter (they don’t copy the entire repo with all the assets) but [native/src/api.rs](https://github.com/Phoenix1504e/Octernships_Project/blob/4a5bab864197ace8da54a11dd070af6854cd144f/native/src/api.rs) and [lib/main.dart](https://github.com/Phoenix1504e/Octernships_Project/blob/4a5bab864197ace8da54a11dd070af6854cd144f/lib/main.dart) are identical to mine

**Comment by beelchester** [comment]
Hey @rustdesk, I have submitted my assignment in the [private repo](https://github.com/rustdesk-org/authenticate-without-polkit-sahilyeole/pull/5). Are you going to review the private repos too?
Btw, amazing work @poopsicles It's really impressive.

**Comment by anupam577** [comment]
@rustdesk 
How many more days will it take for the submission to be reviewed?

**Comment by dibenzepin** [comment]
it's been a while and i think they didn't actually accept anyone, so closing

**Comment by rustdesk** [comment]
Since this one is not as good as https://github.com/rustdesk-org/authenticate-without-polkit-sahilyeole/pull/5#discussion_r1275940856

**Comment by dibenzepin** [comment]
@rustdesk oh that's cool, but that's a private repository, any chance we could get access to the code so we could improve?

**Comment by rustdesk** [comment]
No need to spend more time on this. But if you are really interested, you can try a real project.

**Comment by brambhattabhishek** [comment]
yes write i give some time tough but ..... it is an interesting project ...

**Pull request closed without merging**
