### PR TITLE
Complete Task for Octernship

### PR DESCRIPTION
**Pull request by jonas1ara**
# Complete Task for Octernship

- I read about the rustdesk project
- Set my environment in `Ubuntu 22.04 with GNOME`
- Add the packages `cargo install flutter_rust_bridge_codegen` and `flutter pub add --dev ffigen && flutter pub add ffi` to the project
- Implement the typical hello world in rust and use it from flutter
- Research `polkit` and `pkexec` to run from Rust
- I read the operation of the function `pub fn check_super_user_permission() -> ResultType<bool>` from the file `rustdesk/src/platform/linux.rs`
- Write the function `pub fn print_bash_command_output()` to check if `polkit` is installed and print the output of a bash command `ls -la /root/`
- Use `flutter_rust_bridge_codegen --rust-input native/src/api.rs --dart-output lib/bridge_generated.dart --dart-decl-output lib/bridge_definitions.dart` to generate the code that Flutter will use to invoke Rust functionality.
- Finally I consumed that function from `main.dart`

### I know it can improve my homework performance a lot, but today is the last day to submit it. I am happy to realize that flutter is an exquisite technology and I am very motivated by the possibility of using RUST in a professional and open source project :-)

### CODE REVIEW

**Comment by saaxena** [comment]
hey can anyone tell me do i have to upload my assignment here by forking this repo and creating new branch and then opening pull request.  i dont have any repo generated by github classroom .

**Comment by jonas1ara** [comment]
That doesn't matter, as long as you have your GitHub student account verified, fork this repo and do the PR

**Comment by saaxena** [comment]
so i should create a new branch in fork repo and then do the pr

**Comment by jonas1ara** [comment]
Yes, that’s right

**Comment by saaxena** [comment]
thank you so much for your help

**Comment by rustdesk** [comment]
Thanks, but you ignored.

>  you need to detect if polkit works well, and elevate priviledge with alternative way

**Comment by Jonas-Lara** [comment]
Yes, I think I missed raising the privilege with an alternative way, thanks for the feedback.

**Pull request closed without merging**
